package uk.ac.le.cs.CO7216;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Geographic_Region <br>
 * @version generated on Fri Apr 29 11:51:19 WAT 2016 by Tara
 */

public interface Geographic_Region extends Group {

    /* ***************************************************
     * Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#contains
     */
     
    /**
     * Gets all property values for the contains property.<p>
     * 
     * @returns a collection of values for the contains property.
     */
    Collection<? extends Country> getContains();

    /**
     * Checks if the class has a contains property value.<p>
     * 
     * @return true if there is a contains property value.
     */
    boolean hasContains();

    /**
     * Adds a contains property value.<p>
     * 
     * @param newContains the contains property value to be added
     */
    void addContains(Country newContains);

    /**
     * Removes a contains property value.<p>
     * 
     * @param oldContains the contains property value to be removed.
     */
    void removeContains(Country oldContains);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
