package uk.ac.le.cs.CO7216;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Official_Language <br>
 * @version generated on Fri Apr 29 11:51:19 WAT 2016 by Tara
 */

public interface Official_Language extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#languageName
     */
     
    /**
     * Gets all property values for the languageName property.<p>
     * 
     * @returns a collection of values for the languageName property.
     */
    Collection<? extends Object> getLanguageName();

    /**
     * Checks if the class has a languageName property value.<p>
     * 
     * @return true if there is a languageName property value.
     */
    boolean hasLanguageName();

    /**
     * Adds a languageName property value.<p>
     * 
     * @param newLanguageName the languageName property value to be added
     */
    void addLanguageName(Object newLanguageName);

    /**
     * Removes a languageName property value.<p>
     * 
     * @param oldLanguageName the languageName property value to be removed.
     */
    void removeLanguageName(Object oldLanguageName);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
