package uk.ac.le.cs.CO7216;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Partner <br>
 * @version generated on Fri Apr 29 11:51:19 WAT 2016 by Tara
 */

public interface Partner extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#is_a
     */
     
    /**
     * Gets all property values for the is_a property.<p>
     * 
     * @returns a collection of values for the is_a property.
     */
    Collection<? extends WrappedIndividual> getIs_a();

    /**
     * Checks if the class has a is_a property value.<p>
     * 
     * @return true if there is a is_a property value.
     */
    boolean hasIs_a();

    /**
     * Adds a is_a property value.<p>
     * 
     * @param newIs_a the is_a property value to be added
     */
    void addIs_a(WrappedIndividual newIs_a);

    /**
     * Removes a is_a property value.<p>
     * 
     * @param oldIs_a the is_a property value to be removed.
     */
    void removeIs_a(WrappedIndividual oldIs_a);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
