package uk.ac.le.cs.CO7216;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Fri Apr 29 11:51:19 WAT 2016 by Tara
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Country
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COUNTRY.<p>
     * 
     */
    public static final OWLClass CLASS_COUNTRY = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Country"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Democratic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEMOCRATIC.<p>
     * 
     */
    public static final OWLClass CLASS_DEMOCRATIC = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Democratic"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Dictactorship
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DICTACTORSHIP.<p>
     * 
     */
    public static final OWLClass CLASS_DICTACTORSHIP = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Dictactorship"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Economic_Block
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ECONOMIC_BLOCK.<p>
     * 
     */
    public static final OWLClass CLASS_ECONOMIC_BLOCK = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Economic_Block"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Economic_System
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ECONOMIC_SYSTEM.<p>
     * 
     */
    public static final OWLClass CLASS_ECONOMIC_SYSTEM = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Economic_System"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Export_Partner
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXPORT_PARTNER.<p>
     * 
     */
    public static final OWLClass CLASS_EXPORT_PARTNER = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Export_Partner"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#GDP
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GDP.<p>
     * 
     */
    public static final OWLClass CLASS_GDP = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#GDP"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Geographic_Region
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GEOGRAPHIC_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_GEOGRAPHIC_REGION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Geographic_Region"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Government_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GOVERNMENT_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_GOVERNMENT_TYPE = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Government_Type"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Group
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GROUP.<p>
     * 
     */
    public static final OWLClass CLASS_GROUP = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Group"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Import_Partner
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IMPORT_PARTNER.<p>
     * 
     */
    public static final OWLClass CLASS_IMPORT_PARTNER = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Import_Partner"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Monarchy
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MONARCHY.<p>
     * 
     */
    public static final OWLClass CLASS_MONARCHY = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Monarchy"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Official_Language
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OFFICIAL_LANGUAGE.<p>
     * 
     */
    public static final OWLClass CLASS_OFFICIAL_LANGUAGE = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Official_Language"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Partner
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARTNER.<p>
     * 
     */
    public static final OWLClass CLASS_PARTNER = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Partner"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Yearly_GDP_Percent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class YEARLY_GDP_PERCENT.<p>
     * 
     */
    public static final OWLClass CLASS_YEARLY_GDP_PERCENT = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Yearly_GDP_Percent"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/CountryEconomicAspects.owl#Yearly_GDP_Value
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class YEARLY_GDP_VALUE.<p>
     * 
     */
    public static final OWLClass CLASS_YEARLY_GDP_VALUE = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#Yearly_GDP_Value"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#contains
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINS = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#contains"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#has
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#has"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#has_a
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_A.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_A = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#has_a"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#is_a
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_A.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_A = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#is_a"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#uses
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property USES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_USES = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#uses"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#capitalCity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CAPITALCITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CAPITALCITY = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#capitalCity"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#countryName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COUNTRYNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COUNTRYNAME = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#countryName"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#gdpUSDValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GDPUSDVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GDPUSDVALUE = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#gdpUSDValue"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#languageName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LANGUAGENAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LANGUAGENAME = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#languageName"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#partnerName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PARTNERNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PARTNERNAME = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/CountryEconomicAspects.owl#partnerName"));


}
