package uk.ac.le.cs.CO7216;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Yearly_GDP_Value <br>
 * @version generated on Fri Apr 29 11:51:19 WAT 2016 by Tara
 */

public interface Yearly_GDP_Value extends GDP {

    /* ***************************************************
     * Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#gdpUSDValue
     */
     
    /**
     * Gets all property values for the gdpUSDValue property.<p>
     * 
     * @returns a collection of values for the gdpUSDValue property.
     */
    Collection<? extends Object> getGdpUSDValue();

    /**
     * Checks if the class has a gdpUSDValue property value.<p>
     * 
     * @return true if there is a gdpUSDValue property value.
     */
    boolean hasGdpUSDValue();

    /**
     * Adds a gdpUSDValue property value.<p>
     * 
     * @param newGdpUSDValue the gdpUSDValue property value to be added
     */
    void addGdpUSDValue(Object newGdpUSDValue);

    /**
     * Removes a gdpUSDValue property value.<p>
     * 
     * @param oldGdpUSDValue the gdpUSDValue property value to be removed.
     */
    void removeGdpUSDValue(Object oldGdpUSDValue);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
