package uk.ac.le.cs.CO7216.impl;

import uk.ac.le.cs.CO7216.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultOfficial_Language <br>
 * @version generated on Fri Apr 29 11:51:19 WAT 2016 by Tara
 */
public class DefaultOfficial_Language extends WrappedIndividualImpl implements Official_Language {

    public DefaultOfficial_Language(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#languageName
     */
     
    public Collection<? extends Object> getLanguageName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LANGUAGENAME, Object.class);
    }

    public boolean hasLanguageName() {
		return !getLanguageName().isEmpty();
    }

    public void addLanguageName(Object newLanguageName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LANGUAGENAME, newLanguageName);
    }

    public void removeLanguageName(Object oldLanguageName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LANGUAGENAME, oldLanguageName);
    }


}
