package uk.ac.le.cs.CO7216.impl;

import uk.ac.le.cs.CO7216.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultYearly_GDP_Value <br>
 * @version generated on Fri Apr 29 11:51:19 WAT 2016 by Tara
 */
public class DefaultYearly_GDP_Value extends WrappedIndividualImpl implements Yearly_GDP_Value {

    public DefaultYearly_GDP_Value(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#gdpUSDValue
     */
     
    public Collection<? extends Object> getGdpUSDValue() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GDPUSDVALUE, Object.class);
    }

    public boolean hasGdpUSDValue() {
		return !getGdpUSDValue().isEmpty();
    }

    public void addGdpUSDValue(Object newGdpUSDValue) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GDPUSDVALUE, newGdpUSDValue);
    }

    public void removeGdpUSDValue(Object oldGdpUSDValue) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GDPUSDVALUE, oldGdpUSDValue);
    }


}
