package uk.ac.le.cs.CO7216.impl;

import uk.ac.le.cs.CO7216.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultYearly_GDP_Percent <br>
 * @version generated on Fri Apr 29 11:51:19 WAT 2016 by Tara
 */
public class DefaultYearly_GDP_Percent extends WrappedIndividualImpl implements Yearly_GDP_Percent {

    public DefaultYearly_GDP_Percent(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
