package uk.ac.le.cs.CO7216.impl;

import uk.ac.le.cs.CO7216.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultImport_Partner <br>
 * @version generated on Fri Apr 29 11:51:19 WAT 2016 by Tara
 */
public class DefaultImport_Partner extends WrappedIndividualImpl implements Import_Partner {

    public DefaultImport_Partner(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#is_a
     */
     
    public Collection<? extends WrappedIndividual> getIs_a() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_IS_A,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasIs_a() {
	   return !getIs_a().isEmpty();
    }

    public void addIs_a(WrappedIndividual newIs_a) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_IS_A,
                                       newIs_a);
    }

    public void removeIs_a(WrappedIndividual oldIs_a) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_IS_A,
                                          oldIs_a);
    }


}
