package uk.ac.le.cs.CO7216.impl;

import uk.ac.le.cs.CO7216.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultCountry <br>
 * @version generated on Fri Apr 29 11:51:19 WAT 2016 by Tara
 */
public class DefaultCountry extends WrappedIndividualImpl implements Country {

    public DefaultCountry(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#has
     */
     
    public Collection<? extends Yearly_GDP_Value> getHas() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS,
                                               DefaultYearly_GDP_Value.class);
    }

    public boolean hasHas() {
	   return !getHas().isEmpty();
    }

    public void addHas(Yearly_GDP_Value newHas) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS,
                                       newHas);
    }

    public void removeHas(Yearly_GDP_Value oldHas) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS,
                                          oldHas);
    }


    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#has_a
     */
     
    public Collection<? extends WrappedIndividual> getHas_a() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_A,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHas_a() {
	   return !getHas_a().isEmpty();
    }

    public void addHas_a(WrappedIndividual newHas_a) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_A,
                                       newHas_a);
    }

    public void removeHas_a(WrappedIndividual oldHas_a) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_A,
                                          oldHas_a);
    }


    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#uses
     */
     
    public Collection<? extends Official_Language> getUses() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_USES,
                                               DefaultOfficial_Language.class);
    }

    public boolean hasUses() {
	   return !getUses().isEmpty();
    }

    public void addUses(Official_Language newUses) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_USES,
                                       newUses);
    }

    public void removeUses(Official_Language oldUses) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_USES,
                                          oldUses);
    }


    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#capitalCity
     */
     
    public Collection<? extends String> getCapitalCity() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CAPITALCITY, String.class);
    }

    public boolean hasCapitalCity() {
		return !getCapitalCity().isEmpty();
    }

    public void addCapitalCity(String newCapitalCity) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CAPITALCITY, newCapitalCity);
    }

    public void removeCapitalCity(String oldCapitalCity) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CAPITALCITY, oldCapitalCity);
    }


    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/CountryEconomicAspects.owl#countryName
     */
     
    public Collection<? extends String> getCountryName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COUNTRYNAME, String.class);
    }

    public boolean hasCountryName() {
		return !getCountryName().isEmpty();
    }

    public void addCountryName(String newCountryName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COUNTRYNAME, newCountryName);
    }

    public void removeCountryName(String oldCountryName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COUNTRYNAME, oldCountryName);
    }


}
